global:
  scrape_interval: 15s # Coleta métricas a cada 15 segundos

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend-service:8000'] # Nome do serviço no Docker Compose